
POST http://localhost:4004/motor-de-regras/importBOM  HTTP/1.1
Content-Type: application/json;IEEE754Compatible=true

{
    "BOM":[
        {
            "tipoInstalacao":"C",
            "idTipoOS":"0003",
            "codMaterialSAP":"teste123",
            "qtdMin":"2",
            "qtdMax":"8",
            "pctBom":"1",
            "qtdTol":"0",
            "unidadeConsumo":"UN",
            "aprovacaoClaro":false
        },
        {
            "tipoInstalacao":"T",
            "idTipoOS":"0004",
            "codMaterialSAP":"teste321",
            "qtdMin":"2",
            "qtdMax":"6",
            "pctBom":"0",
            "qtdTol":"4",
            "unidadeConsumo":"UN",
            "aprovacaoClaro":false
        }  
    ]
}
###


PATCH http://localhost:4004/motor-de-regras/BOM(tipoInstalacao=%27C%27,idTipoOS=%270003%27,codMaterialSAP=%27teste321%27)  HTTP/1.1
Content-Type: application/json;IEEE754Compatible=true

{
    "tipoInstalacao":"C",
    "idTipoOS":"0003",
    "codMaterialSAP":"teste321",
    "qtdMin":"2",
    "qtdMax":"18",
    "pctBom":"0",
    "qtdTol":"4",
    "unidadeConsumo":"UN",
    "aprovacaoClaro":false
}
###

GET http://localhost:4004/motor-de-regras/killBOM HTTP/1.1
###
